# Name of the domain bridge, used for node naming and logging
name: turtle_bridge
from_domain: 2
to_domain: 1
topics:
  # Bridge "/target" topic from domain ID 1 to domain ID 2
  target:
    type: geometry_msgs/msg/PointStamped
    reversed: true

  distanceToTarget:
    type: test_multi_id/msg/DistanceToTarget