#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from rclpy.context import Context
from std_msgs.msg import String

def main():
    tester= Pub()
    tester.process()

class StringCallBack():
    def __init__(self, pub, msg):
        self._publisher= pub
        self._msg= String()
        self._msg.data= msg
    
    def __call__(self):
        self._publisher.publish( self._msg )

class Pub():
    def __init__(self):
        pass

    def process(self):
        # Ros initialization
        rclpy.init()
        executor= rclpy.get_global_executor()

        self._nodes= []
        self._test_publishers= []

        for domId, msg, freq in zip( [14, 42], ['salut', 'nounou'], [2.0, 0.3] ) :
            rosContext = Context()
            rosContext.init(domain_id= domId)
            node= Node( f"test{domId}", context=rosContext )
            publisher= node.create_publisher( String, 'test', 10 )
            node.create_timer( freq, StringCallBack( publisher, msg ) )

            executor.add_node( node )
            self._nodes.append( node )

        # Infinite loop:
        executor.spin()

        # Clean stop:
        for node in self._nodes :
            node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()