#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from rclpy.context import Context
from rclpy.signals import SignalHandlerOptions
from std_msgs.msg import String

def main():
    tester= Pub()
    tester.process()

class StringCallBack():
    def __init__(self, pub, msg):
        self._publisher= pub
        self._msg= String()
        self._msg.data= msg
    
    def __call__(self):
        self._publisher.publish( self._msg )

class Pub():
    def __init__(self):
        pass

    def process(self):
        # Ros initialization
        rclpy.init()

        self._nodes= []
        self._test_publishers= []

        for domId, msg in zip( [1, 2], ['salut', 'nounou'] ) :
            rosContext = Context()
            rosContext.init(domain_id= domId)
            node= Node( f"test{domId}", context=rosContext )
            publisher= node.create_publisher( String, 'test', 10 )
            node.create_timer( 0.6, StringCallBack( publisher, msg ) )

            self._nodes.append( node )

        # Infinite loop:
        while rclpy.ok() :
            for node in self._nodes :
                rclpy.spin_once( node )

        # Clean stop:
        for node in self._nodes :
            node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()