# Name of the domain bridge, used for node naming and logging
name: stage_bridge_%robot_X%_to_operator
from_domain: 99
to_domain: 1
topics:

  # ------------------------------------------ RVIZ ------------------------------------------ #

  # Bridge "/robot_marker" topic to the operator domain ID (99)
  robot_marker:
    type: visualization_msgs/msg/Marker
    reversed: true
    qos:
      reliability: reliable
      history: keep_last
      durability: transient_local
      depth: 10

  # Bridge "/map" to the operator domain ID (99)
  map:
    type: nav_msgs/msg/OccupancyGrid
    remap: /%robot_X%/map
    reversed: true
    qos:
      reliability: reliable
      history: keep_last
      durability: transient_local
      depth: 10

    
  # Bridge "/package_deposit_marker" to the operator domain ID (99)
  package_deposit_marker:
    type: visualization_msgs/msg/Marker # To show the packages that have been deposit in the correct zone
    reversed: true

  # Bridge "/package_marker_array" to the operator domain ID (99)
  package_marker_array:
    type: visualization_msgs/msg/MarkerArray # To delete markers for packages taken by the robot
    reversed: true




  # ------------------------------------------ DATA ------------------------------------------ #

  # Bridge "/package_marker" the robot's domain ID (to start a bid)
  package_marker:
    type: visualization_msgs/msg/Marker

  # Bridge "/distanceToTarget" to the operator domain ID (99) (to send a bid)
  distanceToTarget:
    type: communication_test_interfaces/msg/DistanceToTarget
    reversed: true

  # Bridge "/assignedRobot" topic to the robot's domain ID (to assign the task)
  assignedRobot:
    type: std_msgs/msg/Int8



  # ------------------------------------------ DEBUG ----------------------------------------- #
  # Costmap
  local_costmap/costmap:
    type: nav_msgs/msg/OccupancyGrid
    reversed: true
    remap: /%robot_X%/local_costmap/costmap
    qos:
      reliability: reliable
      history: keep_last
      durability: transient_local
      depth: 10
    
  local_costmap/costmap_updates:
    type: map_msgs/msg/OccupancyGridUpdate
    reversed: true
    remap: /%robot_X%/local_costmap/costmap_updates

  # Plan
  transformed_global_plan:
    type: nav_msgs/msg/Path
    reversed: true
    remap: /%robot_X%/transformed_global_plan
  

